---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: httpserver
  labels:
    app: httpserver
spec:
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 0
  replicas: 1
  selector:
    matchLabels:
      app: httpserver
  template:
    metadata:
      labels:
        app: httpserver
    spec:
      containers:
      - name: httpserver
        image: blux2/kubernetes-handson-sample:1.0.0
        env:
        - name: PORT
          valueFrom:
            configMapKeyRef:
              name: httpserver-configmap
              key: PORT
        - name: HOST
          valueFrom:
            configMapKeyRef:
              name: httpserver-configmap
              key: HOST
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: httpserver-configmap
data:
  PORT: "8081"
