---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: httpserver
  labels:
    app: httpserver
spec:
  replicas: 3
  selector:
    matchLabels:
      app: httpserver
  template:
    metadata:
      labels:
        app: httpserver
    spec:
      containers:
      - name: httpserver
        image: blux2/kubernetes-handson-sample:1.0.1
        volumeMounts:
        - name: httpserver-config
          mountPath: /etc/config
      volumes:
      - name: httpserver-config
        configMap:
          name: httpserver-configmap
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: httpserver-configmap
data:
  myconfig.txt: |-
    I am hungry.
