---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: httpserver
  labels:
    app: httpserver
spec:
  replicas: 3
  selector:
    matchLabels:
      app: httpserver
  template:
    metadata:
      labels:
        app: httpserver
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 1
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app
                  values:
                  - httpserver
                  operator: In
              topologyKey: kubernetes.io/hostname
      containers:
      - name: httpserver
        image: blux2/kubernetes-handson-sample:1.1.5
        env:
        - name: PORT
          valueFrom:
            configMapKeyRef:
              name: httpserver-configmap
              key: PORT
        resources:
          requests:
            memory: "256Mi"
            cpu: "10m"
          limits:
            memory: "256Mi"
            cpu: "10m"
        readinessProbe:
          httpGet:
            path: /health
            port: 8081
          initialDelaySeconds: 5
          periodSeconds: 5
        livenessProbe:
          httpGet:
            path: /health
            port: 8081
          initialDelaySeconds: 10
          periodSeconds: 5
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: httpserver-configmap
data:
  PORT: "8082"
  HOST: "localhost"
---
apiVersion: v1
kind: Service
metadata:
  name: httpserver-external
spec:
  type: NodePort
  selector:
    app: httpserver
  ports:
    - port: 8081
      targetPort: 8081
      nodePort: 30599
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: httpserver-pdb
spec:
  maxUnavailable: 10%
  selector:
    matchLabels:
      app: httpserver
