apiVersion: v1
kind: Pod
metadata:
  labels:
    app: httpserver
  name: httpserver
spec:
  containers:
  - name: httpserver
    image: blux2/kubernetes-handson-sample:1.1.2
    readinessProbe:
      httpGet:
        path: /health
        port: 8080
      initialDelaySeconds: 5
      periodSeconds: 5
