apiVersion: v1
kind: Pod
metadata:
  labels:
    app: httpserver
  name: httpserver
spec:
  containers:
  - name: httpserver
    image: blux2/kubernetes-handson-sample:1.1.2
    resources:
      requests:
        memory: "15Gi"
        cpu: "10m"
      limits:
        memory: "15Gi"
        cpu: "10m"
