apiVersion: batch/v1
kind: Job
metadata:
  name: date
spec:
  template:
    spec:
      containers:
      - name: date
        image: ubuntu:22.04
        command: ["cur"]
      restartPolicy: Never
  backoffLimit: 4

