---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: httpserver
  labels:
    app: httpserver
spec:
  replicas: 3
  selector:
    matchLabels:
      app: httpserver
  template:
    metadata:
      labels:
        app: httpserver
    spec:
      containers:
      - name: httpserver
        image: blux2/kubernetes-handson-sample:1.0.1
        volumeMounts:
        - name: httpserver-secret
          mountPath: /etc/config
      volumes:
      - name: httpserver-secret
        secret:
          secretName: httpserver-secret
---
apiVersion: v1
kind: Secret
metadata:
  name: httpserver-secret
data:
  myconfig.txt: |-
    SSBhbSBodW5ncnkuCg==
