prometheus:
  prometheusSpec:
    additionalScrapeConfigs:
      - job_name: http-server
        scrape_interval: 10s
        static_configs:
        - targets:
          - httpserver.develop.svc.cluster.local:8080
