---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: httpserver
  labels:
    app: httpserver
spec:
  replicas: 1
  selector:
    matchLabels:
      app: httpserver
  template:
    metadata:
      labels:
        app: httpserver
    spec:
      containers:
      - name: httpserver
        image: blux2/kubernetes-handson-sample:1.0.0
        env:
        - name: PORT
          valueFrom:
            secretKeyRef:
              name: httpserver-secret
              key: PORT
---
apiVersion: v1
kind: Secret
metadata:
  name: httpserver-secret
data:
  myconfig.txt: |-
    I am hungry.
